package com.example.tyraye.dennis.demoTest;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MovieDBSelTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void movieDBSelTest() {
    driver.get("http://54.235.49.14:3000/");
    driver.manage().window().maximize();
    driver.findElement(By.cssSelector(".addLangForm > input")).click();
    driver.findElement(By.cssSelector(".addLangForm > input")).sendKeys("TestLang");
    driver.findElement(By.cssSelector("button:nth-child(4)")).click();
//    driver.findElement(By.cssSelector(".left:nth-child(7) tr:nth-child(9)")).click();
    driver.findElement(By.cssSelector("div:nth-child(1)")).click();
    driver.findElement(By.name("Language ID")).click();
    driver.findElement(By.name("Language ID")).sendKeys("12");
    driver.findElement(By.cssSelector("button:nth-child(2)")).click();
    driver.findElement(By.cssSelector("form:nth-child(11) > input")).click();
    driver.findElement(By.cssSelector("form:nth-child(11) > input")).sendKeys("AcaDemy Dinosaur ");
    driver.findElement(By.cssSelector("form:nth-child(1) > input:nth-child(1)")).click();
    driver.findElement(By.cssSelector("form:nth-child(1) > input:nth-child(1)")).sendKeys("1");
    driver.findElement(By.cssSelector("div:nth-child(9) input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("div:nth-child(9) input:nth-child(2)")).sendKeys("GENERAL");
    driver.findElement(By.cssSelector("input:nth-child(3)")).sendKeys("KENOBI");
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    driver.findElement(By.cssSelector("div:nth-child(1)")).click();
    driver.findElement(By.cssSelector("form:nth-child(11) > input")).click();
    driver.findElement(By.cssSelector("form:nth-child(11) > input")).sendKeys("FFF");
//    driver.findElement(By.cssSelector(".left:nth-child(14) > tbody > tr:nth-child(1)")).click();
    driver.findElement(By.cssSelector("div:nth-child(1)")).click();
  }
}
